#57 add products and related variations by vendor
atlp-rwanda/ecommerce-app-legends-fe pull request #28
Opened 2023-05-07 02:49 UTC by Kevin-ishimwe

#### What does this PR do?
add products and related variations by vendor functionality
#### Description of Task to be completed?
-seller can choose category to add product to
-seller can add product
-seller adds product variation after adding products
#### How should this be manually tested?

choose category
http://localhost:5173/dashboard/products/categories
should redirect you to add product and subsequently variations

![Capture](https://user-images.githubusercontent.com/107407670/236655066-2f0b0319-23bf-486c-904c-ad5ee26683ee.PNG)

2023-05-09 15:32 UTC, Evaristekanova approved these changes

2023-05-09 15:51 UTC, BenoitIT approved these changes

2023-05-09 16:22 UTC, Aimeana100 approved these changes
It works @Kevin-ishimwe , However according to the backend implementation, you may add  a way to create multiple images for a product.

2023-05-09 16:23 UTC, Aimeana100 requested changes
Add multiple Images too for the product.

2023-05-10 11:16 UTC, Christa22 approved these changes

2023-05-10 11:16 UTC, Christa22 approved these changes

2023-05-10 11:44 UTC, mansurissa approved these changes

2023-05-10 11:45 UTC, merged