Ch router setup
atlp-rwanda/ecommerce-app-legends-fe pull request #9
Opened 2023-04-20 18:05 UTC by ngoma3

##What does this PR do
>> setup and configure the routes
>> create dummy route for Login and / page to test configuration
>> 
##How to run it 
>> clone this repo
>> run npm install
>> run npm run dev

2023-04-20 19:26 UTC, Kevin-ishimwe approved these changes
great work

2023-04-20 21:37 UTC, Aimeana100 commented
How do we test ??

2023-04-20 21:57 UTC, Aimeana100 approved these changes
it works!

2023-04-21 07:08 UTC, nicele08 requested changes

2023-04-21 07:08 UTC, nicele08 commented on README.md
> +git clone https://github.com/your-username/ecommerce-web-app.git
Use the real link: `https://github.com/atlp-rwanda/ecommerce-app-legends-fe.git`

2023-04-21 07:08 UTC, nicele08 commented on src/components/Navbar.jsx
> +        </Link>
For navigation, I recommend you to use `NavLink` as it has features that can allow you to style active/pending links easily.
Here is documentation about [NavLink](https://reactrouter.com/en/main/components/nav-link)

2023-04-21 07:08 UTC, nicele08 commented on src/components/Navbar.jsx
> +        <br />
Using `<br />` tags to create line breaks in HTML code is not considered best practice as it can make the code less semantic and harder to maintain. Instead, I recommended to use TailwindCSS to achieve the desired layout.

2023-04-21 07:08 UTC, nicele08 commented on src/main.jsx
> +]);
Let's put this in new component which returns a RouterProvider component with the router object created using createBrowserRouter.

2023-04-21 07:08 UTC, nicele08 commented on src/views/Login.jsx
> +      <br />
same as here; avoid using `<br />` you can use tailwindcss like `mt-{n}` to achieve the same layout.

2023-04-21 07:08 UTC, nicele08 commented on src/views/Login.jsx
> +        <br />
same as here; remove `<br />`

2023-04-21 07:08 UTC, nicele08 commented on src/views/Login.jsx
> +        <br />
same as here; remove `<br />`

2023-04-21 07:08 UTC, nicele08 commented on src/views/Login.jsx
> +          className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500  p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-40
Create a custom Input component to avoid code duplication and make your code more reusable.

You'll create a new Input component that accepts the following props: label, type, id, and placeholder. The component renders a label and an input field with the specified props, as well as a default className that provides consistent styling across your application.

Then you will use the custom Input component in your code like this:

```javascript
      <Input label="Email" type="text" id="email" placeholder="Enter your email" />
      <Input label="Password" type="password" id="password" placeholder="Enter your password" />
```

2023-04-23 22:47 UTC, FabCode67 approved these changes
great

2023-04-24 01:05 UTC, Aimeana100 approved these changes
Perfect 👍

2023-04-24 10:03 UTC, Christa22 approved these changes

2023-04-24 12:50 UTC, mansurissa approved these changes

2023-04-24 12:51 UTC, merged